### ISSUE TITLE
[Feature request] - Providers (like Google, Facebook) for auth

### ISSUE THREAD

**Issue by var-che** [oskar-gmerek/surreal-sveltekit#4]
It would be useful to have providers for auth stuff, mostly because people can abuse create user functionality, and spam the DB with them. It's also the standard for most apps to have those.

**Comment by oskar-gmerek** [comment]
Thanks for this suggestion. While social login is a beneficial feature, it falls outside the scope of this project. This project attempts to show basic integration of SurrealDB with SvelteKit + eventually very light extras. Social login is not built in SurrealDB nor SvelteKit and need a lot of code to maintain or use 3rd party service which is also out of scope of this project.

**Comment by oskar-gmerek** [comment]
Thanks for this suggestion. While social login is a beneficial feature, it falls outside the scope of this project. This project attempts to show basic integration of SurrealDB with SvelteKit + eventually very light extras. Social login is not built in SurrealDB nor SvelteKit and need a lot of code to maintain or use 3rd party service which is also out of scope of this project.
